<a href="https://colab.research.google.com/github/BenCheung1/Pytorch_Sandbox/blob/main/Python_Numpy_Primer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
# Numeric Python (NumPy)
# Python Lists, Flexible python list is computationally expensive
# numpy array is more optimized
pylist = ["Ben",2,3,True,5] # python list
print (pylist[2])
# ndarray = n-dimensional array
np1 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])
print (np1)
# Create numpy array using Range function
np1.shape
np2 = np.arange(10)
print (np2)
# Create numpy array using Steps
np3 = np.arange(0,10,2)
print (np3)
# numpy Zeros function
np4 = np.zeros(10)
print (np4)
# multidimensional arrays of zeros
np5 =np.zeros((2,10))
print (np5)
# multidimensional Full array of 6s
np6=np.full((2,10),6)
print(np6)
# convert python list to np
my_list =[1,2,3,4,5]
np8=np.array(my_list)
print(np8)

3
[-3 -2 -1  0  1  2  3  4  5  6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]
[1 2 3 4 5]


In [2]:
# CH2 SLICING NUMPY ARRAYS
np1 = np.array([1,2,3,4,5,6,7,8,9])
# Return 2,3,4,5
print (np1[1:5])
# print from something to the end
print(np1[3:])
# return negative slice
print(np1[-3:-1])
# steps
print(np1[1:5:2])
# steps on the entire array
print(np1[::2])
# Slide a 2-dimensiona array
np2 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
# Pull out a single item
print(np2[1,2])
# slice a 2-D Array get 2,3
print (np2[0:1, 1:3])
# slice from both rows get 2,3 and 7,8
print (np2[0:2, 1:3])

[2 3 4 5]
[4 5 6 7 8 9]
[7 8]
[2 4]
[1 3 5 7 9]
8
[[2 3]]
[[2 3]
 [7 8]]


In [3]:
# CH3 UNIVERSAL FUNCTIONS (UFUNCS) IN NUMPY
print (np1)
# Square Root of each element
print (np.sqrt(np1))
# Absolute Value
print (np.absolute(np1))
# Exponential
print (np.exp(np1))
# Logarithm
print (np.log(np1))
# Logarithm base 10
print (np.log10(np1))
# Logarithm base 2
print (np.log2(np1))
# Min/Max
print (np.max(np1))
print (np.min(np1))
# Mean
print (np.mean(np1))
# Median
print (np.median(np1))
# Standard Deviation
print (np.std(np1))
# Sign positive or negative
print (np.sign(np1))
# Trig sin, cosine, log
print (np.sin(np1))
print (np.cos(np1))
print (np.tan(np1))

[1 2 3 4 5 6 7 8 9]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[1 2 3 4 5 6 7 8 9]
[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]
[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]
9
1
5.0
5.0
2.581988897471611
[1 1 1 1 1 1 1 1 1]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619
  0.87144798 -6.79971146 -0.45231566]


In [4]:
# CH4 COPY VERSUS VIEW
np3 = np.array([1,2,3,4,5,6,7,8,9])
# Create a View
np9 = np3.view()
print(f'Original NP3 {np3}')
print(f'Original NP9 {np9}')
# Changing an element of the Original changes the VIEW
# The "copy"/view is "connected" to the original
# Changing either the view or copy updates the other one.
np3[0] = 10
print(f'Modified NP3 {np3}')
print(f'Modified NP9 {np9}')
# Create a copy of original
np10 = np3.copy()
print(f'Original NP3 {np3}')
print(f'Original NP10 {np10}')
# Changing an element of the Original does not change the COPY
# The "copy"/view is not "connected" to the original
np3[0] = 32
print(f'Modified NP3 {np3}')
print(f'Modified NP10 {np10}')

Original NP3 [1 2 3 4 5 6 7 8 9]
Original NP9 [1 2 3 4 5 6 7 8 9]
Modified NP3 [10  2  3  4  5  6  7  8  9]
Modified NP9 [10  2  3  4  5  6  7  8  9]
Original NP3 [10  2  3  4  5  6  7  8  9]
Original NP10 [10  2  3  4  5  6  7  8  9]
Modified NP3 [32  2  3  4  5  6  7  8  9]
Modified NP10 [10  2  3  4  5  6  7  8  9]


In [5]:
# Ch5 SHAPE AND RESHAPE NUMPY ARRAYS
# Create 1-D numpy array and get shape
np11 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print (np11)
print (np11.shape)

# Create 2-D array and get Shape, (rows/ columns)
np12 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print (np12)
print (np12.shape)

# Reshape 1D array into a 2-D array
np13 = np11.reshape(3,4)
print (np13)
print (np13.shape)

# Reshape 3-D
np14 = np11.reshape(2,3,2)
print (np14)
print (np14.shape)

# Flatten to 1-D
np15 = np14.reshape(-1)
print (np15)
print (np15.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [11]:
# CH 6 ITERATING THROUGH NUMPY ARRAYS
# 1-d Numpy Array
print (np11)
for x in np11:
  print (x)
# 2-D Array
print (np12)
for x in np12:
  # print rows
  print (x)
  for y in x:
    # print elements
    print (y)
# 3-D Array
print (np14)
for x in np14:
  print (x)
  for y in x:
    print (y)
    for z in y:
      print (z)
# Iterate on each scalar element
# Use np.nditer()
for x in np.nditer(np14):
  print (x)
#

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
2
3
4
5
6
7
8
9
10
11
12
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[1 2 3 4 5 6]
1
2
3
4
5
6
[ 7  8  9 10 11 12]
7
8
9
10
11
12
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[[1 2]
 [3 4]
 [5 6]]
[1 2]
1
2
[3 4]
3
4
[5 6]
5
6
[[ 7  8]
 [ 9 10]
 [11 12]]
[7 8]
7
8
[ 9 10]
9
10
[11 12]
11
12
1
2
3
4
5
6
7
8
9
10
11
12


In [16]:
# CH 7 SORTING NUMPY ARRAYS
# np.sort(), Numerical Sort
np16 = np.array([6,7,4,9,0,2,1])
print (np16)
print (np.sort(np16)) #returns a copy
print (np16) # original is unchanged
# Alphabetical Sort
np17 = np.array(["Alpha","November","Zebra","Delta","Sierra"])
print (np17)
print (np.sort(np17))
# Booleans T/F
np18 = np.array([True,False, False,True])
print (np18)
print (np.sort(np18))
# Return a copy not change the original
# 2D Array
np19 = np.array([[6,7,1,9],[8,3,5,0]])
print (np19)
print (np.sort(np19))


[6 7 4 9 0 2 1]
[0 1 2 4 6 7 9]
[6 7 4 9 0 2 1]
['Alpha' 'November' 'Zebra' 'Delta' 'Sierra']
['Alpha' 'Delta' 'November' 'Sierra' 'Zebra']
[ True False False  True]
[False False  True  True]
[[6 7 1 9]
 [8 3 5 0]]
[[1 6 7 9]
 [0 3 5 8]]


In [22]:
# CH 8 SEARCHING FOR NUMPY ARRAYS THE EASY WAY
# SEARCH, Use 1-D Array NP20
np20 = np.array([1,2,3,4,5,3,7,8,9,10,11,12])
x = np.where(np20 == 3) # return a tuple of the index # where 3 is
print (np20)
print (x) # returns the index # of where 3 is, not item itself
print (x[0])
print (np20[x[0]]) # to get item itself access via x[0]

# Return the Even Items
x = np.where(np20 % 2 == 0)
print (x) # the 1st, 3rd, 7th, 9th & 11th items are even
print (x[0])

# Return the Odd Items
x = np.where(np20 %2 == 1)
print (x)
print (x[0])


[ 1  2  3  4  5  3  7  8  9 10 11 12]
(array([2, 5]),)
[2 5]
[3 3]
(array([ 1,  3,  7,  9, 11]),)
[ 1  3  7  9 11]
(array([ 0,  2,  4,  5,  6,  8, 10]),)
[ 0  2  4  5  6  8 10]


In [27]:
# CH9 HOW TO FILTER NUMPY ARRAYS With Boolean Index Lists
# use Np 11, filter first 2 elements
x = [True, True, False, False, False, False, False, False, False, False, False, False, ]
print (np11)
print (np11[x])

# Create Filtered List
filtered_list = []
for element in np11:
  if element %2 ==0: # create a filter for even #s
    filtered_list.append(True)
  else:
    filtered_list.append(False)
print (np11)
print (filtered_list)
print (np11[filtered_list])

# Numpy has a built in shortcut for the filtered_list
filtered_list = np11 % 2 == 0
print (np11)
print (filtered_list)
print (np11[filtered_list])
# Machine learning, data mining often requires filtering

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[1 2]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[False, True, False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10 12]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[False  True False  True False  True False  True False  True False  True]
[ 2  4  6  8 10 12]
