<a href="https://colab.research.google.com/github/BenCheung1/Pytorch_Sandbox/blob/main/Pytorch_TensorOps_MathOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import torch
import numpy as np
## Tensor Math Operations: Add, Subtract, Multiply, Divide, Remainders, Exponents
## Shorthand, Longhand, Reassignment
tensor_1 = torch.tensor([1,2,3,4])
tensor_2 = torch.tensor([5,6,7,8])
## Addition
tensor_1 + tensor_2


tensor([ 6,  8, 10, 12])

In [30]:
## Sub Fuction (Subtraction)
torch.sub(tensor_2,tensor_1)

tensor([4, 4, 4, 4])

In [29]:
## Addition Longhand
torch.add (tensor_1, tensor_2)

## subtraction
tensor_2-tensor_1


tensor([4, 4, 4, 4])

In [31]:
## Multiplication
tensor_2 * tensor_1
## Multiplication Longhand
torch.mul (tensor_2, tensor_1)


tensor([ 5, 12, 21, 32])

In [35]:
## Division
torch.div(tensor_2, tensor_1)
tensor_2/tensor_1

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [37]:
## Remainder Modulus
tensor_2 % tensor_1
torch.remainder (tensor_2, tensor_1)

tensor([0, 0, 1, 0])

In [38]:
## Exponents / Power
torch.pow(tensor_1, tensor_2)

tensor([    1,    64,  2187, 65536])

In [39]:
## Another way to write longhand
tensor_1.add (tensor_2)

tensor([ 6,  8, 10, 12])

In [44]:
## Reassignment
tensor_1 + tensor_2
tensor_1
## Tensor_1 = Tensor_1 + Tensor_2
tensor_1.add_(tensor_2)
tensor_1

tensor([ 6,  8, 10, 12])