<a href="https://colab.research.google.com/github/BenCheung1/Pytorch_Sandbox/blob/main/Pytorch_TensorOps_ReshapeViewSlice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import torch
import numpy as np
mytorch = torch.arange(10)
mytorch
## RESHAPE & VIEW Tensor Operations
mytorch = mytorch.reshape(2,5)
mytorch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
## Reshape if you don't know the number of items using "-1"
mytorch2 = torch.arange (15)
mytorch2 = mytorch2.reshape(3,-1)
mytorch2
mytorch3 = mytorch2.view (3,5)
mytorch3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [22]:
## With reshape and view they will update if the underlying Tensor changes
mytorch5 = torch.arange (10)
mytorch5[1] = 31415
mytorch6 = mytorch5.reshape(2,5)
mytorch6

tensor([[    0, 31415,     2,     3,     4],
        [    5,     6,     7,     8,     9]])

In [25]:
## SLICES
mytorch7 = torch.arange (10)
mytorch7[7]
## GRAB A SLICE
mytorch8 = mytorch7.reshape (5,2)
mytorch8[:,1]
## RETURN A COLUMN
mytorch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])