<a href="https://colab.research.google.com/github/BenCheung1/Pytorch_Sandbox/blob/main/Pytorch_Tensors_Proj1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import torch
import numpy as np
py_list = [[1,2,3,4,5], [6,7,8,9,10]]
py_list
nmpy_array = np.random.rand(3,4)
nmpy_array.dtype
tensor_2d = torch.randn (3,4)
tensor_2d

tensor([[-0.4895, -0.2304,  0.3400, -0.5366],
        [ 1.2837,  1.8767, -0.4278,  0.7571],
        [ 0.0751, -1.0198, -0.3901,  0.1954]])

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## create tensor out of numpy array
my_tensor = torch.tensor(nmpy_array)
my_tensor

tensor([[0.6736, 0.9084, 0.6127, 0.8503],
        [0.0623, 0.6294, 0.7299, 0.3964],
        [0.6348, 0.5988, 0.6151, 0.5502]], dtype=torch.float64)